### ISSUE TITLE
jest를 이용한 유닛테스트 관련 이슈

### ISSUE THREAD

**Issue by Hoonveloper** [assetbox/assetbox#12]
이번 스프린트에서 유닛테스트를 담당하고 있는데 몇가지 질문이 생겨서 이슈 남깁니다.

1. 각 모노레포에서 모두 유닛테스트를 진행할텐데, root에서 jest 라이브러리를 설치하고 모노레포에서  root에 있는 jest 라이브러리를 공용으로 사용할 수 있도록 하는게 좋은 방법일 것 같은데 어떻게 생각하시나요?

2. 테스트 진행시 testEnv와 같은 디렉토리 내부에서 가상의 asset 저장 스페이스를 만들고 해당 디렉토리에서 테스팅 하려고 하는데 어떤 방식이 좋을지 의견 있으신가요?

**Comment by Hoonveloper** [comment]
(2)에서 mocking 해서 메모리에 가상으로 만들면, 개발자끼리 테스팅환경을 공유할 수 있나요? 아니면 각 개발자마다 만들어야 하나요?
demo레포를 사용하여 개발자끼리 테스팅 환경을 공유하고 같은 demo레포 안에서 테스트하면 좋지 않을까 라는 생각이 듭니다.

**Comment by gronxb** [comment]
demo 레포지토리 사용 시 유닛보단 통합 테스트가 될 것 같은데 저도 생각 좀 해보겠습니다.

**Comment by gronxb** [comment]
https://github.com/assetbox/assetbox/pull/15
