### ISSUE TITLE
[cli] manager package dev & build

### ISSUE THREAD

**Issue by moonchop** [assetbox/assetbox#2]
## 설명
cli에서 manager 패키지를 개발용 서버로 열거나 build 한다.

## 할 일
- [x] cli에서 createViteServer를 이용하여 vite 서버 생성하여 개발용 서버로 열기
- [x] build : 미정

**Comment by gronxb** [comment]
https://github.com/assetbox/assetbox/pull/13
https://github.com/assetbox/assetbox/pull/6
