### ISSUE TITLE
[trpc] Asset 추가 API

### ISSUE THREAD

**Issue by Hoonveloper** [assetbox/assetbox#39]
파일 추가를 trpc통해 하려다보니, trpc는 input으로 mulipart/form-data를 지원하지 않는다고 하네요.
아래 링크를 참조하면 될 것 같습니다.
https://github.com/trpc/trpc/discussions/658

그렇다면 Manage 에서 fs모듈로 구현한 함수로 asset을 추가해야 할까요?

**Comment by moonchop** [comment]
POST 메소드로 manage에서 asset을 전달해줘서
trpc에서 fs모듈을 사용하면 안되나요??

**Comment by Hoonveloper** [comment]
말씀드린 방법이 그 방법입니다.
링크 보시면 multipart/form-data를 지원하지 aaset 전달이 안됩니다.

**Comment by moonchop** [comment]
그러네요 S3도입은 지금 상황에서 힘든것같습니다.
base64로 인코딩해서 전달하는 방법은 가능할 것 같은데, 4mb의 제한이 있는경우도 있다고 하네요. 
일단 이 방법으로 하는건 어떤가요?

**Comment by Hoonveloper** [comment]
s3는 어떤 말씀이신가요?

**https://github.com/mesmerlord/nejdej/blob/7c60dce17d626b6a4f2eb375eb3b23ffc7cac076/src/server/routers/photos.ts#L18**

민수님 말씀대로 일단 이 방법이 최선이겠네요

**Comment by moonchop** [comment]
그부분은 넘겨도 될것같습니다. 제가 잘못이해한 부분이에요
